### ISSUE TITLE
Does this build without lib32stdc++6 on new Debian?

### ISSUE THREAD

**Issue by mkrupczak3** [LacledesLAN/gamesvr-blackmesa#2]
Is the build dependency pegged to a certain version of debian, and if not, does lib32stdc++6 need to be added to the list of tools to install in the Dockerfile?

I think these 32-bit libraries that many Steam games depend on may have been deprecated in later versions of Debian/Linux. 

A container I'm building based off of this one is failing to build, possibly for this reason:
![Build Fail](https://preview.redd.it/yj78o8dis1m51.png)

I may submit a PR soon if I find adding this to my Dockerfile fixes the build

https://developer.valvesoftware.com/wiki/SteamCMD#32-bit_libraries_on_64-bit_Linux_systems

https://wiki.facepunch.com/gmod/Linux_Dedicated_Server_Hosting

**Comment by dudleycodes** [comment]
@mkrupczak3 I'm afraid I can't see the screenshot of your build failure.

**Comment by dudleycodes** [comment]
I'll keep updating this thread as time goes by today - since builds take time and I like being methodical my process will be to try a single tweak, walk away for a bit, check the results, and rinse-and-repeat. My goal will be to update the base image to the latest, reasonable version of Debian-slim and then see if we can remove the `lib32stdc++6` package without issue.

I'll be using Windows 10 Pro x64 v2004 with Docker via WSL2.  Here are the commands I'll be using to build/test:

```shell
docker pull lacledeslan/steamcmd:linux; docker build . -f linux.Dockerfile -t lltest/gamesvr-blackmesa --no-cache --build-arg BUILDNODE=$env:computername; 
docker run -it --rm lltest/gamesvr-blackmesa ./ll-tests/gamesvr-blackmesa.sh;
docker image prune;
```

**Steps Taken**

1. Update the base image to `debian:buster-slim` from `debian:stretch-slim`:

    ```shell
    E: Unable to locate package lib32tinfo5
    ```

2. Try removing `lib32tinfo5` since it isn't available in buster's default sources; test script reports and error:

    ```shell
    [FAIL] - 'readline dependencies found'
    ```

    Looking at the server output:

    ```shell
    WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
      Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable deadline.
    ```

3. After googling, looks like the [GSM devs worked around this by swaping in`libtinfo5:i386`](https://github.com/GameServerManagers/LinuxGSM/issues/2503); since this image adds `i386` architecture via `dpkg` let's give this a try:

    ```shell
    [TEST RESULTS]

    [PASS] - 'Sever started executing'
    [PASS] - 'loaded dedicated.so'
    [PASS] - 'Server is not boot-looping'
    [PASS] - 'readline dependencies found'
    [PASS] - 'Server is not running under root'
    [PASS] - 'srcds_run loaded Black Mesa'
    [PASS] - 'Server was able to load map'
    [PASS] - 'srcds_run succesfully hibernated'
    [PASS] - ''say STARTING COMMAND TESTS' should result in 'Console: STARTING COMMAND TESTS' (loop iterations: 0)'
    
    [OUTCOME]
    All checks passed!
    ```
Cool; we're updated to `debian:buster-slim`. I've committed it to this repo.

To be continued...

**Comment by dudleycodes** [comment]
4. Let's try removing `lib32stdc++6` and see what happens:

    ```shell
    [OUTCOME]
    
    All checks passed!
    ```

    @mkrupczak3 Looks like `lib32stdc++6` isn't needed at all.

5. What about `libstdc++6`?... nope!

    ```shell
     [OUTCOME]
     
     All checks passed!
     ```

6. And `libstdc++6:i386`?... yup

    ```shell
    Auto detecting CPU
    Using default binary: ./srcds_linux
    Failed to open dedicated_srv.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
    ```

Pushing a commit that removes `lib32stdc++6` and `libstdc++6`.

**Comment by dudleycodes** [comment]
### Actions Taken So Far

- Base image bumped up to `debian:buster-slim` from `debian:stretch-slim`.
- Packages `lib32stdc++6` and `libstdc++6` have been removed.

### Next Steps

@mkrupczak3 let me know if this addresses the issues you encountered; if it doesn't I'll see what else we can figure out.

**Comment by mkrupczak3** [comment]
Hey, so I think I could have been mistaken. I was building yesterday, and the error I had seemed to be related to the line in the Dockerfile:

COPY ./.steamcmd-cache/linux /output

...and not the 32 bit binaries, though I mistaked it for that error due to the similar error messages and some careless google-ing

I tried the following instead:

COPY --chown=SteamCMD:root ./.steamcmd-cache/linux /output

...but that didn't work either, so I ended up commenting out the line and the rest of the build ran fine, but a later line where it copys from "output" to "app" doesn't actually copy anything now, of course. 

Thanks for taking a look at this, sorry for the wild goose chase. I'm not sure how to proceed for fixing my build from here though

---------------------------------------------------------------------------------------------------------------------------------------

Error from earlier:

Step 4/23 Copy ./.steamcmd-cache/linux/output
COPY failed: stat /var/lib/docker/tmp/docker-builder843888606/.steamcmd-cache/linux: no such file or directory

https://i.redd.it/yj78o8dis1m51.png

**Comment by dudleycodes** [comment]
@mkrupczak3 

Ok, so it looks like you're working on [github.com/mkrupczak3/day-of-infamy-dedicated](https://github.com/mkrupczak3/day-of-infamy-dedicated) and are using this `gamesvr-blackmesa` as a source reference for your build.

The issue you're hitting is that the directory `.steamcmd-cache/linux` doesn't exist in your repo. This is totally fine, we use the caching mechanism at our LAN parties in case the Internet goes out but we have to rebuild the image for some reason. So this is something you can skip, in fact, you can skip a lot of the extra steps we take.

I'd trim down your Dockerfile to the following and take it from here:

```Dockerfile
# escape=`
FROM lacledeslan/steamcmd:linux as doi-builder

# Download DOI via SteamCMD
RUN echo "\n\nDownloading Day of Infamy via SteamCMD"; `
        mkdir --parents /output; `
        /app/steamcmd.sh +login anonymous +force_install_dir /output +app_update 462310 validate +quit; `

#=======================================================================`
FROM debian:stable-slim

RUN dpkg --add-architecture i386 &&`
    apt-get update && apt-get install -y `
        ca-certificates lib32gcc1 lib32stdc++6 libstdc++6 libstdc++6:i386 locales locales-all tmux &&`
    apt-get clean &&`
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*;

ENV LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8

LABEL maintainer="mkrupczak <t3l3tubie@gmail.com>" `
      org.label-schema.schema-version="1.0" `
      org.label-schema.vendor="Matts Bytes" `
      org.label-schema.description="Day of Infamy Dedicated Server" `
      org.label-schema.vcs-url="https://github.com/mkrupczak3/day-of-infamy-dedicated"

# Set up Enviornment
RUN useradd --home /app --gid root --system DOI &&`
    mkdir -p /app/ll-tests &&`
    chown DOI:root -R /app;

# `RUN true` lines are work around for https://github.com/moby/moby/issues/36573
COPY --chown=DOI:root --from=doi-builder /output /app
RUN true

COPY --chown=DOI:root ./dist/linux/ll-tests /app/ll-tests
RUN chmod +x /app/ll-tests/*.sh;

USER DOI

RUN echo $'\n\nLinking steamclient.so to prevent srcds_run errors' &&`
        mkdir --parents /app/.steam/sdk32 &&`
        ln -s /app/bin/steamclient.so /app/.steam/sdk32/steamclient.so;

WORKDIR /app

CMD ["/bin/bash"]

ONBUILD USER root
```

and take it from there.

**Comment by dudleycodes** [comment]
@mkrupczak3 I'm going to close this issue as it's not related directly to this repo. Feel free to ping me directly if you have quick questions.
